"""
generate_synthetic_data.py

A small, self-contained **shape demo** of the synthetic training corpus: three
fixed records showing the exact input/output format and the gold invariant. The
real corpus was generated by an LLM following the spec in
`DATA.md` and `sg_pii_reference_bank.md`; the live, spec-driven generator is
`generate_synthetic_data.ipynb`. This file needs no dependencies and no API key,
so you can run it to see the format and the integrity check in action.

Method (see DATA.md for the full write-up):
  1. Each record is an SP Group call-centre transcript for a realistic scenario at
     a difficulty tier (normal / medium / hard, plus "negative" calls with no PII).
     Variety teaches the model the many ways PII is spoken (whole, in fragments,
     digit-by-digit, spelled out, read back for confirmation).
  2. The `entities` dict lists, per label, the exact surface strings that are PII.
     Duplicates are meaningful -- a value that occurs N times in the text is listed
     N times (the "gold invariant"), so read-backs are represented. Addresses are
     tagged compositionally: the street name, block, unit, and postal code are
     separate labels (and disjoint substrings).
  3. Records are written one JSON object per file:
         {"input": <transcript>, "output": {"entities": {<label>: [<str>, ...]}}}

Each record is verified with `compute_standalone_counts` -- the SAME gold-integrity
checker the notebook and the original batch scripts used -- so the listed count of
every value matches its true occurrence count in the text (short values like a bare
block number are not double-counted inside longer ones).

Output: data/generated/<name>.json  (offline; the data/ folder is gitignored).
Writes to the data/generated/ staging folder. Review the records, then move approved
ones into data/train/synthetic/ (or data/val/synthetic/) before running build_splits.py.

Usage:
  python finetuning/data_prep/generate_synthetic_data.py
"""

import json
import re
from collections import Counter
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[2] / "data" / "generated"

LABELS = ["sg_phone_number", "sg_nric_fin", "sg_address", "sg_postal_code",
          "sg_address_unit_number", "sg_address_block_number", "email_address",
          "account_number", "full_name"]

# Each record: (filename, tier, transcript, entities).
# Values are listed once per occurrence so gold counts match the text exactly.
RECORDS = [
    (
        "example_normal_address_update.json", "normal",
        "SPEAKER_00: Good afternoon, SP Group, this is Mei speaking, how can I help you?\n"
        "SPEAKER_01: Hi, I've moved and want to update my address.\n"
        "SPEAKER_00: Sure, what's the new address?\n"
        "SPEAKER_01: Block 45 Riverside Road, #12-08, Singapore 610045.\n"
        "SPEAKER_00: Block 45 Riverside Road, unit 12-08, postal 610045 -- updated.\n"
        "SPEAKER_01: Great, thank you.\n"
        "SPEAKER_00: You're welcome, have a good day.",
        {
            # street / block / unit / postal tagged separately (compositional);
            # the address is spoken twice, so each value is listed twice.
            "sg_address": ["Riverside Road", "Riverside Road"],
            "sg_address_block_number": ["Block 45", "Block 45"],
            "sg_address_unit_number": ["#12-08", "12-08"],
            "sg_postal_code": ["610045", "610045"],
            "full_name": ["Mei"],
        },
    ),
    (
        "example_medium_phone_readback.json", "medium",
        "SPEAKER_00: SP Group, Daniel speaking.\n"
        "SPEAKER_01: Hi, please update my contact number.\n"
        "SPEAKER_00: Go ahead.\n"
        "SPEAKER_01: It's nine one two three four five six seven.\n"
        "SPEAKER_00: Let me read that back, 9123 4567?\n"
        "SPEAKER_01: Yes that's right.\n"
        "SPEAKER_00: Done, thank you.",
        {
            # spoken form and the digit read-back both count (gold invariant)
            "sg_phone_number": ["nine one two three four five six seven", "9123 4567"],
            "full_name": ["Daniel"],
        },
    ),
    (
        "example_negative_billing_faq.json", "normal (negative)",
        "SPEAKER_00: Good morning, SP Group, Charmaine here.\n"
        "SPEAKER_01: Hi, does a ceiling fan use much electricity compared to aircon?\n"
        "SPEAKER_00: A fan uses far less than air conditioning, generally.\n"
        "SPEAKER_01: Good to know, thanks.\n"
        "SPEAKER_00: You're welcome.",
        {},  # no PII: negatives teach the model not to over-redact
    ),
]


def core_format(s):
    return s.rstrip(".,?!- ")


def compute_standalone_counts(values, text):
    """{value: standalone occurrence count}; longest-first, covered-span exclusion,
    so a short value (bare block ``45``) is not double-counted inside a longer one
    it sits in (``610045``, ``Block 45``). Same checker as the notebook."""
    distinct = sorted(set(values), key=len, reverse=True)
    covered, counts = [], {}
    for v in distinct:
        core = core_format(v)
        if not core:
            counts[v] = 0
            continue
        pat = re.compile(r"(?<![A-Za-z0-9])" + re.escape(core) + r"(?![A-Za-z0-9])")
        spans = []
        for m in pat.finditer(text):
            ms, me = m.start(), m.end()
            if any(cs <= ms and me <= ce for cs, ce in covered):
                continue
            spans.append((ms, me))
        counts[v] = len(spans)
        covered.extend(spans)
    return counts


def check_gold_invariant(text, entities):
    """Return a list of problems; empty list == clean."""
    problems = []
    unknown = set(entities) - set(LABELS)
    if unknown:
        problems.append(f"unknown label key(s): {sorted(unknown)}")
    intended = Counter(v for vals in entities.values() for v in vals)
    actual = compute_standalone_counts(list(intended), text)
    for v, n in intended.items():
        if actual.get(v, 0) != n:
            problems.append(f"{v!r}: listed {n}x but occurs {actual.get(v, 0)}x (standalone)")
    return problems


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    any_problem = False
    for fname, tier, text, entities in RECORDS:
        problems = check_gold_invariant(text, entities)
        status = "OK" if not problems else "PROBLEM: " + "; ".join(problems)
        any_problem = any_problem or bool(problems)
        record = {"input": text, "output": {"entities": entities}}
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            json.dump(record, f, ensure_ascii=False)
        gold = sum(len(v) for v in entities.values())
        print(f"wrote {fname:<45} tier={tier:<20} gold={gold:<3} [{status}]")
    print(f"\n{len(RECORDS)} records -> {OUT_DIR}")
    if any_problem:
        print("Some records failed the gold invariant -- fix before using.")


if __name__ == "__main__":
    main()
